version: '2'
services:
  hexo: # 容器名,可根据需要修改
    container_name: hexo
    restart: always # 启动方式
    image: spurin/hexo # 镜像勿动
    environment:
      hexo_SERVER_PORT: 4000 # 缺省的端口号
    ports:  # 端口映射
      - 4000:4000
    volumes: # 磁盘映射
      # 这个镜像将 workspace 设置为了 /app, 我们需要将它持久化到宿主机上
      # 映射位置 主机位置:/app:rw
      - /root/blog:/app:rw
  nginx:
    restart: always # 启动方式
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    links:
      - hexo:hexo # 注意这里需将 hexo 服务的 hostname 注入进去 
    volumes: # 将配置文件及 web 静态文件挂载出来
      # 替换以下 文件夹 宿主机位置:docker容器内部位置
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /var/www/html:/var/www/html
      - /var/www:/var/www
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - hexo # 需要等 hexo 服务成功启动后再启动 nginx
    
